### ISSUE TITLE
Move code into user directory

### ISSUE THREAD

**Issue by luceos** [flagrow/users-list#1]
User directory has an identical logic as this extension. We should dry up and move this code base into the user directory extension.

**Comment by Ralkage** [comment]
@luceos so as far as functionality goes, are you moving the current features in this extension to the user directory extension? I would assume that if the user has certain permissions tied to their user group such as sending emails, activating users, etc, this could be done in the forum-end instead of the admin-end?

**Comment by luceos** [comment]
I'm not sure what your question is. Both extensions do much of the same. We can create a shared component and make the one for the forum protected with permissions.

As this is a revived extension it has not much priority.

Does it even make sense to maintain this with the Reflar extension under active development?
